### PR TITLE
Fixes #22 (Removed hardcoded path)

### LINKED ISSUE #22: global installation is not working because of hardcoded path of prototypes
Hi,
I've installed (apparently successfully, few warnings about unmet dependencies) extendscriptr, but when I try to run a simple:

`$ extendscriptr --script ./test.js --output ./test_enc.js`

I get this error:

```
Running extendscriptr with following options:
--script: ./test.js
--output: ./test_enc.js
--target: undefined (optional)
fs.js:584
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open './node_modules/extendscript.prototypes/lib/extendscript.prototypes.js'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
    at Object.<anonymous> (/usr/local/lib/node_modules/extendscriptr/index.js:27:29)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:429:10)
    at startup (node.js:139:18)
```

Any idea about the reason why this occurs?
Thank you!

Davide

### PR DESCRIPTION
**Pull request by GitBruno**
This should do it, have only tested in my env

### CODE REVIEW

**Comment by fabianmoronzirfas** [comment]
That is cool. I try to run a test ASAP

**Comment by fabianmoronzirfas** [comment]
Please don't mix topics. Removing the hardcoded path has nothing to do with typescript. Please reset to https://github.com/ExtendScript/extendscriptr/pull/36/commits/c6fddf8b4e001ac1260034fabadcc3fe2d311685

**Comment by GitBruno** [comment]
Sorry, I kept working away. So that is why they use feuture branches! 

Will sort it out and add an org guideline, thanks!

**Comment by fabianmoronzirfas** [comment]
Thank you. We are still having a problem installing this globally though.

**Pull request merged**
